#!/usr/bin/env php
<?php

//use Symfony\Component\Dotenv\Dotenv;

require __DIR__ . '/vendor/autoload.php';

//(new Dotenv)->load(__DIR__ . '/.env');

$app = new \Symfony\Component\Console\Application;

$app->add(new \App\Command\GreeterCommand);

$app->run();
